spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to prod service "
  contactDetails:
    name: "Rod - Developer"
    email: "rod@gmail.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384